import type { City } from "./types";

export const CITIES: Record<string, City> = {
  nyc: {
    slug: "nyc",
    name: "New York City",
    lat: 40.7769,
    lon: -73.874,
    tempUnit: "F",
    bracketSize: 2,
  },
  chicago: {
    slug: "chicago",
    name: "Chicago",
    lat: 41.9742,
    lon: -87.9073,
    tempUnit: "F",
    bracketSize: 2,
  },
  dallas: {
    slug: "dallas",
    name: "Dallas",
    lat: 32.8471,
    lon: -96.8518,
    tempUnit: "F",
    bracketSize: 2,
  },
  miami: {
    slug: "miami",
    name: "Miami",
    lat: 25.7959,
    lon: -80.287,
    tempUnit: "F",
    bracketSize: 2,
  },
  seattle: {
    slug: "seattle",
    name: "Seattle",
    lat: 47.4502,
    lon: -122.3088,
    tempUnit: "F",
    bracketSize: 2,
  },
  atlanta: {
    slug: "atlanta",
    name: "Atlanta",
    lat: 33.6407,
    lon: -84.4277,
    tempUnit: "F",
    bracketSize: 2,
  },
  london: {
    slug: "london",
    name: "London",
    lat: 51.5054,
    lon: 0.0554,
    tempUnit: "C",
    bracketSize: 1,
  },
  lucknow: {
    slug: "lucknow",
    name: "Lucknow",
    lat: 26.8467,
    lon: 80.9462,
    tempUnit: "C",
    bracketSize: 1,
  },
  seoul: {
    slug: "seoul",
    name: "Seoul",
    lat: 37.5665,
    lon: 126.978,
    tempUnit: "C",
    bracketSize: 1,
  },
  warsaw: {
    slug: "warsaw",
    name: "Warsaw",
    lat: 52.1657,
    lon: 20.9671,
    tempUnit: "C",
    bracketSize: 1,
  },
  shanghai: {
    slug: "shanghai",
    name: "Shanghai",
    lat: 31.2304,
    lon: 121.4737,
    tempUnit: "C",
    bracketSize: 1,
  },
};
